# Site settings
title: Phong's Portfolio
heeader: Home
email: hoangphong1132000@gmail.com
url: https://github.com/NVH-Phong/nvh-phong.github.io
description: "I am a skilled engineer specializing in product design, offering a range of professional services: 1) CAD Solutions: I transform sketches into precise product renderings using advanced computer design software. 2) 3D Printing: I provide 3D printing-ready files for rapid prototyping, ensuring a seamless transition from digital designs to tangible prototypes. 3) Mechanical Engineering Consulting: I offer expert problem-solving and consultation services in mechanical engineering. From concept to final product, I am committed to delivering high-quality solutions tailored to your needs."
keywords: "your keywords, separated by commas"
skills: "Engineer - CAD - 3D printing - Programming"
meta_author: Hoang Phong

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# # Footer settings
# footer:
#   copyright: Dr. Henry Jekyll
#   location: Location
#   social: Around the Web
#   credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100009778117166
  - title: github
    url: https://github.com/NVH-Phong
  - title: linkedin
    url: https://www.linkedin.com/in/nvhphong/

# Postal address (add as many lines as necessary)
address:
  - line: Mount Waverley
  - line: Melbourne VIC 3149

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
